app:
  config:
    version: 3

server:
  port: 8080

spring:
  application:
    name: gateway-service
  rabbitmq:
    password: guest
    username: guest
    host: localhost
    port: 5672

# Eureka
eureka:
  client:
    registry-fetch-interval-seconds: 5
    register-with-eureka: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/

  instance:
    instance-id: zuul-service


# Zuul
zuul:
  routes:
    todo-service: /api/todos/**


ribbon:
  eureka:
    enabled: true

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'


# Logging
logging:
  level:
    root: warn
    com.melardev: trace
    org.springframework.cloud.netflix.zuul: debug
